spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: none
      ddl-auto: none
    properties:
      hibernate.format_sql: true # para aparecer o formato sql no console